on:
  workflow_call:
    inputs:
      checkov_version:
        required: true
        type: string
      publicMessage:
        required: true
        type: string
    secrets:
      secretMessage:
        required: true

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install checkov==${{ inputs.checkov_version }}
      - name: CodeCheckout
        uses: actions/checkout@v3
      - name: List Directory Files
        run: |
          Get-ChildItem -Recurse
      - name: Run Checkov Scan
        run: |
          checkov --directory ${{ github.workspace }}
  extraCommands:
    name: ExtraComando
    runs-on: ubuntu-latest
    needs: scan
    defaults:
      run:
        shell: pwsh
    steps:
      - name: PowershellCommand1
        run: |
          dir env: | Format-List
      - name: PowershellCommand2
        run: |
          Write-Host "Publich Message is :"
          Write-Host ${{ inputs.publicMessage }}
          Write-Host "Secret Message is :"
          Write-Host ${{ secrets.secretMessage }}
